// ===== Data index red (item yang bisa direveal) =====
// urutan array ini = urutan gambar: index 0 = assets/red/0.png (Golden Koi Statue, termahal)
// sampai index terakhir = termurah. Sesuaikan urutan ini kalau red.json berubah.
const redItems = [
  { name: "Golden Koi Statue", value: 22668888 },
  { name: "Pendragon Model", value: 20171210 },
  { name: "Eternal Heart", value: 1314520 },
  { name: "Antique Suitcase", value: 577777 },
  { name: "Unknown Access Card", value: 366112 },
  { name: "White Dragon King", value: 300000 },
  { name: "Ghostfire Wisp", value: 260423 },
  { name: "Nine-Bite Snack Box", value: 240208 },
  { name: "Portable Folding Screen", value: 239342 },
  { name: "Preserved Flower Wreath", value: 200201 },
  { name: "Slender Lotus Vase", value: 101860 },
  { name: "Lustrous Jade", value: 81088 },
  { name: "Thoth USB Drive", value: 76008 },
  { name: '"Geometric" Decor', value: 61803 },
  { name: "Chaotic Core", value: 61740 },
  { name: "K01 Model", value: 59440 },
  { name: "Whalesong", value: 52000 },
  { name: "Teardrop", value: 50000 },
  { name: "Starshaker", value: 31618 },
  { name: "Crunchy Tempura Rice Bowl", value: 29977 },
];

// ===== Data index gold (item yang bisa direveal) =====
// urutan array ini = urutan gambar: index 0 = assets/gold/0.png (Giovanni's Gilded Statue, termahal)
// sampai index terakhir = termurah. Sesuaikan urutan ini kalau gold.json berubah.
const goldItems = [
  { name: "Giovanni's Gilded Statue", value: 271827 },
  { name: "Flatbread", value: 202798 },
  { name: "Canned Imaginadough", value: 124816 },
  { name: "Golden Arowana", value: 111111 },
  { name: "Coco Stripe", value: 101537 },
  { name: "A Moment's Pause", value: 88888 },
  { name: "Scepter Called Prestige", value: 77777 },
  { name: "Blue and White Porcelain Vase", value: 62456 },
  { name: "Orrery", value: 51077 },
  { name: "Asahi Inori Figurine", value: 30264 },
  { name: "Sea Salt Deep in the Heart", value: 30211 },
  { name: "Your Fitness Buddy!", value: 27246 },
  { name: "Wheelchair Model", value: 27159 },
  { name: "Kokoro Rider L1 - Ultimate Skill", value: 22847 },
  { name: "Kokoro Rider L2 - Nimbus Flash", value: 22770 },
  { name: "Whisperseed", value: 22336 },
  { name: "Kokoro Rider L3 - Spartan Spirit", value: 22297 },
  { name: "Kaleidoscope", value: 21012 },
  { name: "Vine-Pattern Chopsticks", value: 20238 },
  { name: "Oceanic Dewdrops", value: 19926 },
  { name: "Cloudcutter", value: 18288 },
  { name: "Crown Called Nobility", value: 18193 },
  { name: "Universal Adapter", value: 18031 },
  { name: "Spring Sheath", value: 15309 },
  { name: "Blueflame Spark Plug", value: 15108 },
  { name: "Snowfall Emerald", value: 15037 },
  { name: "Weather Guide", value: 15024 },
  { name: "Knight Decal", value: 12164 },
  { name: "Cubox Technologies Stylus", value: 12116 },
  { name: "Cubox Technologies Power Bank", value: 11981 },
  { name: "Freewire Cable", value: 11974 },
  { name: "Crimson Gem", value: 9938 },
  { name: "Laurel Crown", value: 7648 },
  { name: "Grand Slam Hand Roll", value: 7610 },
  { name: "Silent Petal", value: 7547 },
  { name: "Cubox Technologies Smartwatch", value: 7500 },
  { name: "Starfish", value: 5555 },
  { name: "Page 23", value: 5047 },
  { name: "Light Cube", value: 5041 },
  { name: "Sunset Pearl", value: 4975 },
];
